### ISSUE TITLE
Can't use as a module

### ISSUE THREAD

**Issue by fabioconti** [ahmednooor/halkaBox.js#10]
Hi, 
I suggest adding exports to use this as a module in webpack, this could be really really useful
Thanks in advance,
Fabio

**Comment by ahmednooor** [comment]
@fabioconti  thanks for your input. can you please check the files in the zip and confirm that the halkaBox is being exported? thanks.

```
node index.js
```


[module-exports.zip](https://github.com/ahmednooor/halkaBox.js/files/1576469/module-exports.zip)

**Comment by fabioconti** [comment]
@ahmednooor it prints stuff, but doesn't seem to init galleries :(

**Comment by fabioconti** [comment]
the problem seems to be here:
```
// collecting all the anchor tags having data-hb attribute with their respective values
imageLinks = document.getElementsByClassName(selector),
```
I used data-hb selector and not class, but data-hb attribute is ignored in the code :)
I'm goin to correct this in my html output, but I suppose it's better to use the data-hb attribute, at leat I think it's a cleaner solution

**Comment by ahmednooor** [comment]
@fabioconti  thanks for your input. actually i changed `data-hb` to `class` for backwards compatibility and ease of use. most new comers to html usually only know about a handful of attributes such as id and class (personal experience). besides class is almost used on every element so why introduce more weight to the html while we can get the work done without it. 

i have added the feature in the new release (link below). closing this issue now. feel free to report any future bugs/issues.

`module.exports` added.
[1.2.0](https://github.com/ahmednooor/halkaBox.js/releases/tag/1.2.0)
