### ISSUE TITLE
[Feature Request] Add option to destroy instance

### ISSUE THREAD

**Issue by jefrydco** [ahmednooor/halkaBox.js#12]
It will be better if there is a method that will destroy the current instance, use case example is when user change the theme between night and dark it should be re instantiate

**Comment by ahmednooor** [comment]
@jefrydco  thanks for your input.
is this what you mean by destroy instance?

```javascript
halkaBox.destroy = function(selector='class_name') {
    // remove event listeners on a.class_name tags which open the overlay
    // remove internal event listeners of overlay template
    // remove overlay html template appended to the body for that specific instance/gallery
}
```

**Comment by jefrydco** [comment]
@ahmednooor Yup, that was right. Actually I try to wrap this library with Vue.js but it seems there is no destroy option.

**Comment by ahmednooor** [comment]
@jefrydco  ok. i will try to implement it as soon as i can.

**Comment by ahmednooor** [comment]
@jefrydco  please check attached zip and let me know if this satisfies the request.

[with_api.zip](https://github.com/ahmednooor/halkaBox.js/files/2058352/with_api.zip)

USAGE:
```javascript
var gallery = halkaBox.run("class-name", { /* options if any */});
gallery.open(0 /* index of the image to open first is zero */);
gallery.next();
gallery.prev();
gallery.close();
gallery.destroy();
```
