### ISSUE TITLE
Gesture to close on touch devices

### ISSUE THREAD

**Issue by shoesforindustry** [ahmednooor/halkaBox.js#14]
A suggestion to perhaps have some sort of gesture based closure of the overlay on touch based devices? 
A two finger Pinch to close or swipe up or both ?

**Comment by ahmednooor** [comment]
@shoesforindustry  thanks. will try to implement it in the next release. possibly swipe down to close gesture. pinching is for zooming and will require a lot of tinkering with the zoom section of code which i don't want to touch any time soon.

**Comment by ahmednooor** [comment]
@shoesforindustry 

- feature added in version [1.4.1](https://github.com/ahmednooor/halkaBox.js/releases/tag/1.4.1)
- it is disabled by default. you can use it by enabling it in options like so, `swipeDownToClose: true` (see readme for options usage).

closing now.

**Comment by shoesforindustry** [comment]
Thanks Ahmed, that looks good, just a small reminder, many (iOS at least) programs seem to be settling on a swipe up to close, perhaps both directions could be catered for?

**Comment by ahmednooor** [comment]
@shoesforindustry 

What you are suggesting is good UX, but right now i don't have any closing animation implemented, to let the user know that swiping up or down will close the lightbox (animations like lowering opacity or size as the user swipes farther up or down etc.), and instead it just disappears without giving any hint to the user, which is irritating (to me at least). That is why i was hesitant to put it in and that is why it is currently disabled by default.

I will (hopefully in a future release) try to add the relevant animation and the swipe up/down to close will make more sense.

For now i will add the 'swipe up to close' similar to 'swipe down' but they will be disabled by default.

**Comment by ahmednooor** [comment]
https://github.com/ahmednooor/halkaBox.js/commit/bc4f88d3e5714d4f466ca096b81e55f805cadd22
^ `swipeUpToClose` added in v1.5.0
