### ISSUE TITLE
wheelhandler is too sensitive on desktop

### ISSUE THREAD

**Issue by darrenjacoby** [ahmednooor/halkaBox.js#15]
Hi,

Thanks for the work on this.

One thing I noticed is that the wheelhandler for desktop is super sensitive. Is there any way to disable the wheelhandler, or at least slow it down on desktop via the config? 

https://github.com/ahmednooor/halkaBox.js/blob/master/src/halkaBox.js#L570

**Comment by darrenjacoby** [comment]
For others that may be looking, I've been able to remove the wheelhandler using the following;

```
document.querySelector('#hb-wrapperjs-halkabox').addEventListener('wheel', (event) => {
    event.stopImmediatePropagation();
});
```

**Comment by ahmednooor** [comment]
@darrenjacoby  thanks for your input. I will try to add an option for this in the next release.

**Comment by ahmednooor** [comment]
@darrenjacoby 

- fixed sensitivity of wheel (feel free to test it and share result) https://github.com/ahmednooor/halkaBox.js/blob/075995f4d8ceb7b0a54fbf86d1080d664f5d8a8d/src/halkaBox.js#L557-L561.
- you can also disable wheel by using `nextPrevOnWheel: false` in options (see  readme for options usage).

hope this fixes the issue.
closing now.

**Comment by darrenjacoby** [comment]
@ahmednooor that's great, thank you for this!
