### ISSUE TITLE
Use html5 data-title instead of native title attribute

### ISSUE THREAD

**Issue by drnkwati** [ahmednooor/halkaBox.js#16]
Hi
Can you configure the plugin to get captions from html5 data attribute. 
Like data-title. Getting caption from native title attribute interferes with designs especially when we don't want the title to show on mouse hover. 
thanks

**Comment by ahmednooor** [comment]
@drnkwati  i will hopefully add it soon. till then you can replace the `if` block at line `169` to `179` in `src/halkaBox.js` of your local copy,

https://github.com/ahmednooor/halkaBox.js/blob/master/src/halkaBox.js#L169

with the following block,

```js
if (imageLinks[index].getAttribute("title") || imageLinks[index].getAttribute("data-title")) {
    var captionText = document.createElement("p");
    var caption = 
        imageLinks[index].getAttribute("title") 
        ? imageLinks[index].getAttribute("title") 
        : imageLinks[index].getAttribute("data-title");
    captionText.classList.add("hb-caption");
    captionText.innerHTML = '<span class="hb-caption-text">' + caption + '</span>';
    imageObjects[index].appendChild(captionText);
    if (customOptions.theme === "light") {
        captionText.classList.add("hb-caption-white");
    } else if (customOptions.theme === "dark") {
        captionText.classList.add("hb-caption-black");
    }
}
```

this should do it.

**Comment by drnkwati** [comment]
I use the library from cdn, so I will have to wait until you make a commit.

**Comment by ahmednooor** [comment]
https://github.com/ahmednooor/halkaBox.js/commit/bc4f88d3e5714d4f466ca096b81e55f805cadd22
^ `data-title` added in v1.5.0
