### ISSUE TITLE
Double click/tap to zoom in/out

### ISSUE THREAD

**Issue by hotwheel16** [ahmednooor/halkaBox.js#17]
A common pattern beyond pinch zoom in/out is often doubletap to zoom in/out like on FB or IG. Could you forsee a function for such a feature?

**Comment by mrspartak** [comment]
+

**Comment by ahmednooor** [comment]
@hotwheel16 
@mrspartak 

can you please test the attached version of the script and let me know if it works for you? thanks.

[halkaBox_dbl_tap_zoom.zip](https://github.com/ahmednooor/halkaBox.js/files/3313379/halkaBox_dbl_tap_zoom.zip)

**Comment by mrspartak** [comment]
Tested on my website. Double tap works fine. Pinch zoom works too. But when zoomed in by double tap, pinch zoom is laggy

**Comment by ahmednooor** [comment]
@mrspartak   Thank You.
> Tested on my website. Double tap works fine. Pinch zoom works too. But when zoomed in by double tap, pinch zoom is laggy

I don't think that is being caused by the double tap. It might happen when the image is zoomed in a lot. I don't see specific change in behavior when pinch zoom after double tap on my device. The moving is a bit slow though when the image is quite zoomed in.

**Comment by ahmednooor** [comment]
@hotwheel16 
@mrspartak 

Double tap to zoom in/out added in v1.6.0

https://github.com/ahmednooor/halkaBox.js/commit/049cdbe68c99414876184ea1d1105b3d498883cc

Closing.
