### ISSUE TITLE
Transparent PNG

### ISSUE THREAD

**Issue by vojtasvoboda** [ahmednooor/halkaBox.js#20]
Hello, is there some way how to show white background under the transparent PNG `img` element with let say 20px padding?

I've tried ::before class on img, but it's not working. Then I've tried set background color on `hb-image-div`, but this div is 100% width.

Thanks

Your demo with PNG:

<img width="1254" alt="Snímek obrazovky 2019-11-14 v 13 13 30" src="https://user-images.githubusercontent.com/374917/68856371-9e824580-06e0-11ea-9c16-fb49c2d5eca0.png">

**Comment by ahmednooor** [comment]
@vojtasvoboda 
Hello. I think you should try this,
```css
.hb-image-div img {
    background: white;
}
```
It should work. Thanks.

**Comment by vojtasvoboda** [comment]
Great it works well, thanks :-)

<img width="961" alt="Snímek obrazovky 2019-11-14 v 21 16 14" src="https://user-images.githubusercontent.com/374917/68893569-b4fec000-0725-11ea-9546-897ba870091d.png">
