### ISSUE TITLE
Create gallery items via JSON array

### ISSUE THREAD

**Issue by bjarnef** [ahmednooor/halkaBox.js#22]
Looking at the demos and the documentation it seems it is not possible the define the items/elements as a JSON array from JavaScript in in many other gallery plugins like FancyBox and GLightbox to mention a few.

An example from GLightbox:
https://github.com/biati-digital/glightbox#lightbox-options

This is useful when you want to open a gallery from e.g. a button or a single image which should open a full gallery.

**Comment by ahmednooor** [comment]
@bjarnef 

Thank you for your feedback. I understand what you are saying, but I currently don't have the time/will to implement JSON arrays as input. Although what you are saying can be achieved through current available features as well. Please refer to the demo in the attached zip archive.

Thank you. (Closing)

[demo-halkabox-12-11-2020.zip](https://github.com/ahmednooor/halkaBox.js/files/5527248/demo-halkabox-12-11-2020.zip)
