### ISSUE TITLE
Option for Image List

### ISSUE THREAD

**Issue by zsajjad** [ahmednooor/halkaBox.js#3]
It will be ideally if there is something to display the list of images.

**Comment by ahmednooor** [comment]
@zsajjad  you mean something like "2/4" written on the overlay? like something to tell the number of image the user is currently displaying out of total images in gallery?

**Comment by zsajjad** [comment]
Yes, number of images and an array of images as well, just like camera roll in the bottom.

**Comment by ahmednooor** [comment]
@zsajjad  will add the number of images in next release but the camera roll with thumbnails will clutter the ui and hence wont be simple and lightweight.

**Comment by ahmednooor** [comment]
number of images has been incorporated in release 1.0.0 . array of image thumbnails in the overlay will not be inline with minimal feel. closing issue.

v1.0.0
https://github.com/ahmednooor/halkaBox.js/releases/tag/1.0.0
