### ISSUE TITLE
Some callback for onChange

### ISSUE THREAD

**Issue by zsajjad** [ahmednooor/halkaBox.js#4]
I want to integrate this in my project but we load the images dynamically on the go... If there is some way to pass a callback that fires when slides are changed, it will be very useful for us!

**Comment by ahmednooor** [comment]
@zsajjad  you will have to dynamically load the image links i.e. the anchor tags with data-hb attributes. the preloading in the plugin only starts once the user clicks on any image link to open the lightbox.  the large images arent loaded unless the user clicks on the link to open the lightbox overlay.
Thanks a lot for your interest in this script :)
