### ISSUE TITLE
autoplay

### ISSUE THREAD

**Issue by manouman** [ahmednooor/halkaBox.js#5]
autoplay option it's possible?

**Comment by ahmednooor** [comment]
[halkaBox-with-autoplay.zip](https://github.com/ahmednooor/halkaBox.js/files/1099417/halkaBox-with-autoplay.zip)

@manouman 
Please try the .js file from the attached zip and let me know. thanks.

usage:
`<script>
        halkaBox.run("gallery1", {
            autoplay: true,    // default is false
            autoplayInterval: 5000    // default is 3000. it is in milli seconds.
        });
</script>`

**Comment by manouman** [comment]
Works perfect!

**Comment by ahmednooor** [comment]
Feature provided individually. wont be able to incorporate in the release. closing issue.
