### ISSUE TITLE
List of galleries

### ISSUE THREAD

**Issue by mzaidikhlas** [ahmednooor/halkaBox.js#6]
Is there way to show case a collection of gallery with one picture representing each gallery unlike in the demos where all pictures of the gallery are visible before the gallery is opened?

**Comment by ahmednooor** [comment]
@mzaidikhlas   just add "display: none;" to all the links you don't want to show. and leave the one you want to show. the gallery will start from that image.
CODE:
CSS:
```
.hidden {
    display: none !important;
}
```

HTML:
```
<div>
    <a href="..." data-hb="gallery1"><img src="..."></a>
    <a class="hidden" href="..." data-hb="gallery1"><img src="..."></a>
    <a class="hidden" href="..." data-hb="gallery1"><img src="..."></a>
    <a class="hidden" href="..." data-hb="gallery1"><img src="..."></a>
</div>
```

NOTE: Make sure that the "data-hb" attribute of all the links of a single gallery should be of same value.

**Comment by mzaidikhlas** [comment]
Thank you, I will try it out.
